todo/urls.py
from django.contrib import admin
from django.urls import path
from todoapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.create,name='create'),
    path('dele/<id>',views.dele),
    path('edi/<id>',views.edi),
    path('comp/<id>',views.com_task),
    
    
    
]

todoapp/models.py
from django.db import models

# Create your models here.


class task(models.Model):
    task = models.CharField(max_length=100)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return self.task

todoapp/forms.py
from django import forms
from todoapp.models import task


class create_task(forms.ModelForm):
    class Meta:
        model = task
        fields = '__all__'

todoapp/views.py
from django.shortcuts import render,redirect
from todoapp.forms import create_task
from todoapp.models import task

# Create your views here.

def create(request):
    form = create_task()
    
    if request.method == "POST":
        form = create_task(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        

    data = task.objects.order_by("-id")


    context = {'form':form,'data':data}
    return render(request,'create.html',context)



def dele(request,id):
    da= task.objects.get(id=id)
    da.delete()
    return redirect('/')


def edi(request,id):
    dat=task.objects.get(id=id)
    context = {'data':dat}
    if request.method=='POST':
        form = create_task(request.POST,instance=dat)
        if form.is_valid():
            form.save()
            return redirect('/')
    return render(request,'update.html',context)

def com_task(request,id):
    tsk=task.objects.get(id=id)
    tsk.complete = True if request.GET.get('complete') == 'true' else False
    tsk.save()
    
    return redirect('/')



todoapp/templates/create.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <title>TODOAPP</title>
  <style>
    #id_task {
      width: 30%;
      padding: 10px;
      margin-left: 70%;
    }
  </style>
</head>

<body>
  <h1 align="center">TodoApp</h1>

  <form action="" method="post">
    {% csrf_token %}
    <div id="tsk">
      {{form.task}}
    </div>
    <div class="modal-footer">
      <button type="submit" class="btn btn-primary" data-dismiss="modal">Add</button>
    </div>
  </form>


  <div>
    <table border="1" class="table">
      <tr>
        <th>Task</th>
        <th>Action</th>
        <th>edit</th>
        <th>delete</th>
      </tr>

      {% for i in data %}

      <tr>
        {% if i.complete is True %}

        <td align="center" id="val"><b><strike>{{i.task}}</strike></b></td>
        <td align="center"><a href="/comp/{{i.id}}?complete=false"><button class="btn btn-lg btn-success" id="cr">UnCross</button></a></td>
        <td align="center"><a href="/edi/{{i.id}}"><button class="btn btn-lg btn-warning">Edit</button></a></td>
        <td align="center"><a href="/dele/{{i.id}}"><button class="btn btn-lg btn-danger">Delete</button></a></td>

        {% else %}
        <td align="center" id="val"><b>{{i.task}}</b></td>
        <td align="center"><a href="/comp/{{i.id}}?complete=true"><button class="btn btn-lg btn-success" id="cr">Cross</button></a></td>
        <td align="center"><a href="/edi/{{i.id}}"><button class="btn btn-lg btn-warning">Edit</button></a></td>
        <td align="center"><a href="/dele/{{i.id}}"><button class="btn btn-lg btn-danger">Delete</button></a></td>

        {% endif %}
      
      {% endfor %}
    </table>
  </div>



  <script>


    // function croos() {
    //  var valu=document.getElementById("val").value;

    //   console.log(valu)
    //   alert('value is: ', valu)
    // }





// $(document).ready(function(){
//   $("#cr").click(function(){
//     $("#val").html("<strike>a</strike>");
//   });
// });

  </script>

</body>

</html>

todoapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

todoapp/templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Document</title>
    <style>
        .form-control{
            width: 50%;
            padding: 25px;
            margin: 30px;
            margin-left:20%;
            align-items: center;
            
        }
        .btn-primary{
            width: 100px;
            padding: 5px;
            margin: 30px;
            margin-left:43%;
        }
    </style>
</head>
<body>
    <h1 align="center">update task</h1>
    <form action="" method="post">
        {% csrf_token %}
        <input type="text" value="{{data.task}}" name="task"  class="form-control">
        <button type="submit" class="btn btn-primary">update</button>
    </form>
</body>
</html>